name: flutter_logger
description: "custom talker config"
version: 0.0.5+1
homepage: https://github.com/Anfet/flutter_logger.git

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  talker: ^4.6.3
  sprintf: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
